//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternRegistrationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long ID { get; set; }
        public long InternID { get; set; }
        public long DepartmentID { get; set; }
        public int OralExam { get; set; }
        public int WrittenInterview { get; set; }
        public int Average { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual InternInformation InternInformation { get; set; }
    }
}
